[[normalDict]]
org = '‘'
rep = '“'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '’'
rep = '”'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '......'
rep = '……'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '...'
rep = '…'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '…'
rep = '……'
conditionTarget = 'pretrans_text'
conditionReg = '\A(?![\S\s]*……)'
isReg = false
priority = 0

[[normalDict]]
org = ','
rep = '，'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '?'
rep = '？'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '!'
rep = '！'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '~'
rep = '～'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '&'
rep = '＆'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '・'
rep = '·'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = 'ー'
rep = '—'
conditionTarget = ''
conditionReg = ''
isReg = false
priority = 0

[[normalDict]]
org = '—'
rep = '——'
conditionTarget = 'pretrans_text'
conditionReg = '\A(?![\S\s]*——)'
isReg = false
priority = 0

[[normalDict]]
org = '"([^"]*?)"'
rep = '『$1』'
conditionTarget = 'preproc_text'
conditionReg = '\A[^"]*『[^"]*』[^"]*\z'
isReg = true
priority = 0

[[normalDict]]
org = '"([^"]*?)"'
rep = '『$1』'
conditionTarget = 'preproc_text'
conditionReg = '\A[^"]*「[^"]*」[^"]*\z'
isReg = true
priority = 0

[[normalDict]]
org = '『'
rep = '《'
conditionTarget = 'orig_text'
conditionReg = '《'
isReg = false
priority = 0

[[normalDict]]
org = '』'
rep = '》'
conditionTarget = 'orig_text'
conditionReg = '》'
isReg = false
priority = 0

[[normalDict]]
org = '《'
rep = '『'
conditionTarget = 'orig_text'
conditionReg = '『'
isReg = false
priority = 0

[[normalDict]]
org = '》'
rep = '』'
conditionTarget = 'orig_text'
conditionReg = '』'
isReg = false
priority = 0

[[normalDict]]
org = '“'
rep = '「'
conditionTarget = 'preproc_text'
conditionReg = '「'
isReg = false
priority = 0

[[normalDict]]
org = '”'
rep = '」'
conditionTarget = 'preproc_text'
conditionReg = '」'
isReg = false
priority = 0

[[normalDict]]
org = '‘'
rep = '『'
conditionTarget = 'preproc_text'
conditionReg = '『'
isReg = false
priority = 0

[[normalDict]]
org = '’'
rep = '』'
conditionTarget = 'preproc_text'
conditionReg = '』'
isReg = false
priority = 0

[[normalDict]]
org = '“'
rep = '『'
conditionTarget = 'preproc_text'
conditionReg = '『'
isReg = false
priority = 0

[[normalDict]]
org = '”'
rep = '』'
conditionTarget = 'preproc_text'
conditionReg = '』'
isReg = false
priority = 0

[[normalDict]]
org = '『'
rep = '“'
conditionTarget = 'orig_text'
conditionReg = '“'
isReg = false
priority = 0

[[normalDict]]
org = '』'
rep = '”'
conditionTarget = 'orig_text'
conditionReg = '”'
isReg = false
priority = 0

[[normalDict]]
org = '《'
rep = '“'
conditionTarget = 'orig_text'
conditionReg = '“'
isReg = false
priority = 0

[[normalDict]]
org = '》'
rep = '”'
conditionTarget = 'orig_text'
conditionReg = '”'
isReg = false
priority = 0

[[normalDict]]
org = '‘'
rep = '“'
conditionTarget = 'orig_text'
conditionReg = '“'
isReg = false
priority = 0

[[normalDict]]
org = '’'
rep = '”'
conditionTarget = 'orig_text'
conditionReg = '”'
isReg = false
priority = 0

[[normalDict]]
org = '。）'
rep = '）'
conditionTarget = 'orig_text'
conditionReg = '\A(?![\S\s]*。）)'
isReg = false
priority = 0

[[normalDict]]
org = '。。'
rep = '。'
conditionTarget = 'orig_text'
conditionReg = '\A(?![\S\s]*。。)'
isReg = false
priority = 0

