[[normalDict]]
org = '\A“([\S\s]*)”\z'
rep = '『$1』'
conditionTarget = 'preproc_text'
conditionReg = '\A『[\S\s]*』\z'
isReg = true
priority = 1

[[normalDict]]
org = '\A“([\S\s]*)”\z'
rep = '「$1」'
conditionTarget = 'preproc_text'
conditionReg = '\A「[\S\s]*」\z'
isReg = true
priority = 1

